name: ci_create_tag

on:
  push:
    branches:
      - test #main

jobs:
  tag:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Git Bump Version
        shell: bash
        env:
          GIT_CREDS: ${{secrets.GIT_TOKEN}}
        run: |
          env
          # set -x

          # export git_creds_filepath="$HOME/.git-credentials"
          # echo "$GIT_CREDS" > "$git_creds_filepath"
          # git config --global credential.helper 'store --file='"$git_creds_filepath"''
          # git config --unset-all http.https://github.com/.extraheader #https://stackoverflow.com/a/69979203
          # git config --global user.email "ci_user@git.com"
          # git config --global user.name "CI"
          # export CURRENT_LATEST_TAG=$(git tag | sort --version-sort | tail -n 1)
          # export FUTURE_LATEST_TAG=$(echo $CURRENT_LATEST_TAG | awk 'BEGIN{FS=OFS="."} {$2+=1} 1')
          # git tag -a -m "Version $tag" "$tag"
          # git push origin "$tag"